lab 8

Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


print("Array indexing:")
print("Element at arr[1, 2]:", arr[1, 2])


print("\nFancy indexing:")
indices = np.array([[0, 1], [2, 0]])
print("Elements at indices:", arr[indices])


Array indexing:
Element at arr[1, 2]: 6

Fancy indexing:
Elements at indices: [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


Q2. Execute the 2D array Slicing.

In [ ]:
import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


sliced_arr = arr[0:2, 1:3]
print("Sliced array:")
print(sliced_arr)


Sliced array:
[[2 3]
 [5 6]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [ ]:
import numpy as np


five_dim_array = np.array([1, 2, 3], ndmin=5)

print("Shape of the 5-dimensional array:", five_dim_array.shape)
print("Contents of the 5-dimensional array:")
print(five_dim_array)


Shape of the 5-dimensional array: (1, 1, 1, 1, 3)
Contents of the 5-dimensional array:
[[[[[1 2 3]]]]]


Q4. Reshape the array from 1-D to 2-D array.

In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6])


arr_2d = arr_1d.reshape(2, 3)

print("Original 1D array:")
print(arr_1d)

print("\nReshaped 2D array:")
print(arr_2d)


Original 1D array:
[1 2 3 4 5 6]

Reshaped 2D array:
[[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [ ]:
import numpy as np


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


stacked_array = np.stack((arr1, arr2))
print("Stacked array using np.stack():")
print(stacked_array)


hstacked_array = np.hstack((arr1, arr2))
print("\nHorizontally stacked array using np.hstack():")
print(hstacked_array)


vstacked_array = np.vstack((arr1, arr2))
print("\nVertically stacked array using np.vstack():")
print(vstacked_array)


dstacked_array = np.dstack((arr1, arr2))
print("\nDepth-wise stacked array using np.dstack():")
print(dstacked_array)


Stacked array using np.stack():
[[1 2 3]
 [4 5 6]]

Horizontally stacked array using np.hstack():
[1 2 3 4 5 6]

Vertically stacked array using np.vstack():
[[1 2 3]
 [4 5 6]]

Depth-wise stacked array using np.dstack():
[[[1 4]
  [2 5]
  [3 6]]]


Q6. Perform the searchsort method in Numpy array.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

value_to_insert = 25

insert_index = np.searchsorted(arr, value_to_insert)

sorted_arr = np.insert(arr, insert_index, value_to_insert)

print("Original sorted array:", arr)
print("Sorted array after insertion:", sorted_arr)


Original sorted array: [10 20 30 40 50]
Sorted array after insertion: [10 20 25 30 40 50]


Q7. Create Numpy Structured array using your domain features.

In [2]:
import numpy as np

rental_dtype = np.dtype([
    ('rental_id', 'int'),
    ('customer_name', 'U50'),
    ('vehicle_type', 'U20'),
    ('rental_duration', 'int'),
    ('rental_cost', 'float')
])


rental_data = [
    (1, 'John Doe', 'SUV', 5, 350.0),
    (2, 'Jane Smith', 'Compact', 3, 200.0),
    (3, 'Mike Johnson', 'Minivan', 7, 500.0)
]


rentals_array = np.array(rental_data, dtype=rental_dtype)

print("First rental record:")
print("Rental ID:", rentals_array[0]['rental_id'])
print("Customer Name:", rentals_array[0]['customer_name'])
print("Vehicle Type:", rentals_array[0]['vehicle_type'])
print("Rental Duration:", rentals_array[0]['rental_duration'])
print("Rental Cost:", rentals_array[0]['rental_cost'])


First rental record:
Rental ID: 1
Customer Name: John Doe
Vehicle Type: SUV
Rental Duration: 5
Rental Cost: 350.0


Q8. Create Data frame using List and Dictionary.

In [3]:
import pandas as pd

names = ['Alice', 'Bob', 'Charlie', 'David', 'Emma']
ages = [25, 30, 35, 40, 45]

data = {
    'Name': names,
    'Age': ages
}

df = pd.DataFrame(data)

print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   45


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [4]:
import pandas as pd
import numpy as np


rental_data = {
    'rental_id': [1, 2, np.nan, 4, 5],
    'customer_name': ['John Doe', 'Jane Smith', 'Mike Johnson', np.nan, 'Sarah'],
    'vehicle_type': ['SUV', 'Compact', np.nan, 'Minivan', 'Sedan'],
    'rental_duration': [5, np.nan, 7, 3, np.nan],
    'rental_cost': [350.0, 200.0, np.nan, np.nan, 400.0]
}


df = pd.DataFrame(rental_data)


print("Original DataFrame:")
print(df)


print("\nCheck for missing data (isnull()):")
print(df.isnull())

print("\nCheck for non-missing data (notnull()):")
print(df.notnull())


df_dropna = df.dropna()
print("\nDataFrame after dropping rows with any missing data:")
print(df_dropna)

df_fillna = df.fillna(0)
print("\nDataFrame after filling missing data with 0:")
print(df_fillna)


df_interpolate = df.interpolate()
print("\nDataFrame after interpolating missing values:")
print(df_interpolate)


Original DataFrame:
   rental_id customer_name vehicle_type  rental_duration  rental_cost
0        1.0      John Doe          SUV              5.0        350.0
1        2.0    Jane Smith      Compact              NaN        200.0
2        NaN  Mike Johnson          NaN              7.0          NaN
3        4.0           NaN      Minivan              3.0          NaN
4        5.0         Sarah        Sedan              NaN        400.0

Check for missing data (isnull()):
   rental_id  customer_name  vehicle_type  rental_duration  rental_cost
0      False          False         False            False        False
1      False          False         False             True        False
2       True          False          True            False         True
3      False           True         False            False         True
4      False          False         False             True        False

Check for non-missing data (notnull()):
   rental_id  customer_name  vehicle_type  rental_d

Q10. Perform the Hierarchical Indexing in the above created dataset.

In [ ]:
import pandas as pd
import numpy as np

rental_data = {
    'rental_id': [1, 2, 3, 4, 5],
    'customer_name': ['John Doe', 'Jane Smith', 'Mike Johnson', 'David Brown', 'Emma Davis'],
    'vehicle_type': ['SUV', 'Compact', 'Minivan', 'Sedan', 'SUV'],
    'rental_duration': [5, 3, 7, 2, 4],
    'rental_cost': [350.0, 200.0, 450.0, 300.0, 400.0]
}


df = pd.DataFrame(rental_data)

df.set_index(['rental_id', 'customer_name'], inplace=True)

print("DataFrame with Hierarchical Index:")
print(df)
