In [5]:
import numpy as np


matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)


elementwise_product = np.prod([matrix1, matrix2], axis=0)


matrix_multiplication = np.matmul(matrix1, matrix2)

dot_product = np.dot(matrix1.flatten(), matrix2.flatten())


print("\nElement-wise product (prod):")
print(elementwise_product)

print("\nMatrix multiplication (multiply):")
print(matrix_multiplication)

print("\nDot product (dot):")
print(dot_product)


Matrix 1:
[[0.9438747  0.96767498 0.7329571 ]
 [0.82948097 0.86268031 0.89471349]
 [0.91728806 0.12890949 0.78222869]]

Matrix 2:
[[0.98075716 0.95330329 0.5449849 ]
 [0.31579535 0.8807488  0.33006813]
 [0.13348003 0.20178366 0.79270145]]

Element-wise product (prod):
[[0.92571186 0.92248774 0.39945055]
 [0.26194623 0.75980465 0.29531641]
 [0.12243964 0.02601183 0.62007381]]

Matrix multiplication (multiply):
[[1.32913426 1.8999762  1.41481229]
 [1.20537622 1.73109015 1.44603856]
 [1.04475776 1.14583157 1.16253087]]

Dot product (dot):
4.333242734365971


In [2]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

union_result = np.union1d(array1, array2)

intersection_result = np.intersect1d(array1, array2)

set_difference_result = np.setdiff1d(array1, array2)

xor_result = np.setxor1d(array1, array2)

print("Union:", union_result)
print("Intersection:", intersection_result)
print("Set Difference:", set_difference_result)
print("XOR:", xor_result)


Union: [1 2 3 4 5 6 7]
Intersection: [3 4 5]
Set Difference: [1 2]
XOR: [1 2 6 7]


In [8]:
import numpy as np

array = np.random.randint(10,size=6)

print("Original Array:")
print(array)

cumulative_sum = np.cumsum(array)

cumulative_product = np.cumprod(array)

discrete_difference = np.diff(array, n=3)

unique_elements = np.unique(array)

print("\nCumulative Sum:")
print(cumulative_sum)

print("\nCumulative Product:")
print(cumulative_product)

print("\nDiscrete Difference (with n=3):")
print(discrete_difference)

print("\nUnique Elements:")
print(unique_elements)


Original Array:
[9 5 1 9 5 6]

Cumulative Sum:
[ 9 14 15 24 29 35]

Cumulative Product:
[    9    45    45   405  2025 12150]

Discrete Difference (with n=3):
[ 12 -24  17]

Unique Elements:
[1 5 6 9]


In [9]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

result_zip = np.array([x + y for x, y in zip(array1, array2)])

result_np_add = np.add(array1, array2)

def custom_add(x, y):
    return x + y

add_func = np.frompyfunc(custom_add, 2, 1)
result_custom = add_func(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)

print("\nAddition using zip():")
print(result_zip)

print("\nAddition using np.add():")
print(result_np_add)



Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Addition using zip():
[11 22 33 44 55]

Addition using np.add():
[11 22 33 44 55]


In [10]:
from functools import reduce
import math

elements = [12, 18, 24, 36]

def calculate_lcm(x, y):
    return x * y // math.gcd(x, y)

lcm_result = reduce(calculate_lcm, elements)

gcd_result = reduce(math.gcd, elements)

print("Elements:", elements)
print("LCM:", lcm_result)
print("GCD:", gcd_result)


Elements: [12, 18, 24, 36]
LCM: 72
GCD: 6
